
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.java.main.src/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://ws.java.main.src/", className = "proxy.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://ws.java.main.src/", className = "proxy.ListCompteResponse")
    @Action(input = "http://ws.java.main.src/BanqueService/listCompteRequest", output = "http://ws.java.main.src/BanqueService/listCompteResponse")
    public List<Compte> listCompte();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComte", targetNamespace = "http://ws.java.main.src/", className = "proxy.GetComte")
    @ResponseWrapper(localName = "getComteResponse", targetNamespace = "http://ws.java.main.src/", className = "proxy.GetComteResponse")
    @Action(input = "http://ws.java.main.src/BanqueService/getComteRequest", output = "http://ws.java.main.src/BanqueService/getComteResponse")
    public Compte getComte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertDHtoEURO", targetNamespace = "http://ws.java.main.src/", className = "proxy.ConvertDHtoEURO")
    @ResponseWrapper(localName = "convertDHtoEUROResponse", targetNamespace = "http://ws.java.main.src/", className = "proxy.ConvertDHtoEUROResponse")
    @Action(input = "http://ws.java.main.src/BanqueService/convertDHtoEURORequest", output = "http://ws.java.main.src/BanqueService/convertDHtoEUROResponse")
    public double convertDHtoEURO(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
